### ISSUE TITLE
Ah im to dumb 🤣

### ISSUE THREAD

**Issue by JokersCat** [avengy/discord-captcha-callback-function#2]
So I understand that the Programm searches from the iFrame of the captcha.And the it tries to pop out the captcha key or something I testet it on discord but the only thing it does is resetting the captcha maybe discord sends you a Cookie back.I have to check that tomorrow 😂 (Avengy please write your discord tag in a command I will contact you ☺️)

**Comment by avengy** [comment]
u0z0#7266

**Comment by JokersCat** [comment]
Added you

**Comment by JokersCat** [comment]
Oh wow I think you can use the function to submit the captcha key oh 😂 so I would still need a api for that but thx for it I guess 😂

**Comment by JokersCat** [comment]
Hey so how can I fix that the accounts get locked? xD

**Comment by VersaceXcodes** [comment]
@avengy I added you too can you accept
